### ISSUE TITLE
response error reported

### ISSUE THREAD

**Issue by jaycheunge** [GeorgeVentura/southwest-scraper#1]
I'm trying to run the script and got a response like this:
('Connection aborted.', error(54, 'Connection reset by peer'))

I basically followed the instruction to run a test from 'SFO' to 'LAS' on '2017-05-27'.

Do you already have any knowledge on this error is returned? Did SouthWest change their API?  Appreciate if you have some insights

**Comment by GeorgeVentura** [comment]
I get the same error on OS X. My issue was that python was using an old version of openSSL causing a handshake failure. I fixed it simply by installing python and openSSL with homebrew.

The script is still working.

**Comment by jaycheunge** [comment]
I'm using macOS 10.12.2. When I tried to install openssl, it gave the following information:

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

And it's still not working for me. Did you run into this?

**Comment by GeorgeVentura** [comment]
I never got that message, but I'm running 10.11.4.
Did openssl download but not link correctly? Run `brew list --versions` and see if the newest openssl is listed.

Other then that I essential ran these steps: https://stackoverflow.com/questions/24323858/python-referencing-old-ssl-version

`$ brew update`
`$ brew install openssl`
`$ brew link openssl --force`
`$ brew install python --with-brewed-openssl`

I had to install python with brew after installing openssl and use that python to run the script, because I could succeed to get my original python to reference the newer version of openssl

**Comment by Enuratique** [comment]
I get a 400 response code when the request is made. Did the API key get revoked? I'm also noticing the API key defined in the constant doesn't exactly match what is put in the request header. I tried replacing what's in the request header with what's defined in the API_KEY constant, but got the same result.
